[package]
name = "aresampler"
version = "0.2.4"
edition = "2024"

[[bin]]
name = "aresampler"
path = "src/main.rs"

[dependencies]
aresampler-core = { path = "../aresampler-core" }
anyhow = "1.0"
gpui = "0.2"
gpui-component = "0.4"
hound = "3.5"
image = "0.25"
rodio = "0.19"
